### ISSUE TITLE
Prefetching an already prefetched query with new variables fails when a different query is prefetched in between.

### ISSUE THREAD

**Issue by epiqueras** [relay-tools/relay-hooks#151] opened 2021-02-01 21:34 UTC
https://github.com/Proof-Of-Humanity/proof-of-humanity-web/issues/3#issuecomment-771173088

**Comment by morrys** [comment] 2021-02-02 12:00
hi @epiqueras,
as soon as I can I will take a look at your problem, in the meantime could you check that the problem is also present with version 4.0.0?

**Comment by morrys** [comment] 2021-02-02 14:33
hi @epiqueras,
i just created a PR that solves the problem in version 4.0.0 👍
Soon I intend to officially release the 4.1.0 release with this fix too.

At the moment I prefer not to keep version 3.x active even if in the PR I put a comment how to solve the problem in version 3.7.0

**Comment by epiqueras** [comment] 2021-02-02 16:45
https://github.com/Proof-Of-Humanity/proof-of-humanity-web/issues/3#issuecomment-771775226

**Comment by morrys** [comment] 2021-02-03 23:57
released with version [4.1.0](https://github.com/relay-tools/relay-hooks/releases/tag/v4.1.0) &  [3.7.1](https://github.com/relay-tools/relay-hooks/releases/tag/v3.7.1)

**Closed by morrys** 2021-02-03 23:57 UTC
